#!/usr/bin/env bash
# This script transfers a file from the client to a server using scp

# Check if the required number of arguments (4) are provided
if [ "$#" -lt 4 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Assign the provided arguments to variables
file_path="$1"
server_ip="$2"
username="$3"
ssh_key_path="$4"

# Transfer the file using scp
# -o StrictHostKeyChecking=no: disables strict host key checking, allowing the connection to proceed without prompting for user confirmation.
# -i "$ssh_key_path": specifies the path to the SSH private key to be used for authentication.
scp -o StrictHostKeyChecking=no -i "$ssh_key_path" "$file_path" "$username@$server_ip:~/"
