#!/usr/bin/env bash
# This script configures Nginx to redirect requests to /redirect_me with a 301 status code

# Update the package lists for the latest version of packages and installs the Nginx web server package if it's not already installed
apt-get update
apt-get install -y nginx

# Create a backup of the default Nginx configuration file
cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.bak

# Create the index.html file with the content "Hello World!"
echo "Hello World!" > /var/www/html/index.html

one_line="index index.html;"
multiple_lines="index index.html;\\n location /redirect_me {\\n return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\\n }"

# Use the sed command to replace the line "index index.html;" with the lines stored in the $multiple_lines variable
sudo sed -i "s/${one_line}/|${multiple_lines}/" /etc/nginx/sites-available/default

# Remove the symbolic link in the /etc/nginx/sites-enabled/ directory, which was pointing to the old configuration
rm /etc/nginx/sites-enabled/default

# Create a new symbolic link from the modified configuration file in /etc/nginx/sites-available/default to the /etc/nginx/sites-enabled/ directory
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/

# Reload the Nginx service to apply the new configuration
service nginx reload
