#!/usr/bin/env bash
# This Bash script automates the installation and configuration of HAProxy on the lb-01 server.

# Install HAProxy
apt-get update
apt-get install -y haproxy

# Configure HAProxy
echo "Configuring HAProxy..."
cat << 'EOF' > /etc/haproxy/haproxy.cfg
frontend http-in
	bind *:80
	mode http
	default_backend web-servers

backend web-servers
	balance roundrobin
	mode http
	server 376780-web-01 54.236.53.157:80 check
	server 376780-web-02 52.87.216.90:80 check
EOF

# Restart HAProxy service
servise haproxy restart

# Print the status of the HAProxy service
echo "HAProxy service status:"
service haproxy status

# Print the HAProxy configuration file
echo "HAProxy Configuration File:"
cat /etc/haproxy/haproxy.cfg
