#!/usr/bin/env bash
# This Bash script automates the installation and configuration of HAProxy on the lb-01 server.

# Install HAProxy
sudo apt-get update
sudo apt-get install -y haproxy

# Configure HAProxy
echo "Configuring HAProxy..."
sudo cat << 'EOF' > /etc/haproxy/haproxy.cfg
frontend http-in
	bind *:80
	mode http
	default_backend web-servers

backend web-servers
	balance roundrobin
	mode http
	server web-01 376780-web-01:80
	server web-02 376780-lb-01:80
EOF

# Restart HAProxy service
sudo systemctl restart haproxy

# Enable HAProxy service on system startup
sudo systemctl enable haproxy

# Print the status of the HAProxy service
echo "HAProxy service status:"
sudo systemctl status haproxy

# Print the HAProxy configuration file
echo "HAProxy Configuration File:"
cat /etc/haproxy/haproxy.cfg
