#!/usr/bin/env bash
# This script is displaying "Best School" 10 times with condition
i=1
while [ $i -le 10 ]
do
    if [ $i -eq 9 ]
    then
        printf "Best School\nHi\n"
    else
        echo "Best School"
    fi
    ((i++))
done
