#!/usr/bin/env bash
# displays the time for 12 hours and 59 minutes

# Initialize variables
hour=0
minute=1

while [ "$hour" -le 12 ]; do
    echo "Hour: $hour"
    
    while [ "$minute" -lt 60 ]; do
        echo "$minute"
        ((minute++))
    done

    # Increment hour and reset minute for a new hour
    ((hour++))
    minute=1
done
