#!/usr/bin/env bash
# a Bash script that gives you information about the school file.


# Check if the file exists
if [ -e "school" ]; then
    echo "school file exists"

    # Check if the file is not empty
    if [ -s "school" ]; then
        echo "school file is not empty"

        # Check if the file is a regular file
        if [ -f "school" ]; then
            echo "school is a regular file"
        else
            # If the file is not a regular file (do nothing)
            :
        fi
    else
        echo "school file is empty"
    fi
else
    echo "school file does not exist"
fi
