#!/usr/bin/env bash
# configures an Ubuntu server with some requirements.

# Backup the original hosts file
sudo cp /etc/hosts /etc/hosts.bak

# Change localhost to 127.0.0.2 and facebook.com to 8.8.8.8
sudo sed -i 's/127.0.0.1\tlocalhost/127.0.0.2\tlocalhost/g' /etc/hosts
sudo sed -i 's/\(.*\)facebook.com/\1 8.8.8.8 facebook.com/g' /etc/hosts

# Reload the networking configuration
sudo /etc/init.d/networking restart

# Display a message indicating the changes have been applied
echo "IP configuration changed. Check the hosts file for details."

# Display the updated hosts file
cat /etc/hosts
