#!/usr/bin/env bash
# This script runs the whoami command under the user passed as an argument

# Check if the user argument is provided
if [ $# -ne 1 ]; then
	echo "Usage: $0 <user>"
	exit 1
fi

sudo -u "$1" whoami
