#!/usr/bin/env bash
# Bash script to configure Nginx to run as nginx user and listen on port 8080


# Update the Nginx configuration file(s) to run Nginx as the 'nginx' user
sed -i 's/^user .*/user nginx;/' /etc/nginx/nginx.conf

# Update the Nginx configuration file to listen on all active IPs on port 8080
sed -i 's/listen 80;/listen 8080;/' /etc/nginx/sites-available/default

# Check if Nginx is running and reload the configuration
if [ "$(pgrep nginx)" ]; then
    nginx -s reload
else
    service nginx start
fi
