#!/usr/bin/env bash
# Script to configure Nginx to run as nginx user and listen on port 8080
sed -i 's/user www-data/user nginx/' /etc/nginx/nginx.conf
chmod 644 /etc/nginx/nginx.conf
sed -i 's/\b80\b/8080/g' /etc/nginx/sites-available/default
pkill apache2
sudo -u nginx service nginx start
