#!/usr/bin/env bash
# This script generates an RSA key pair with the private key named 'school', using a key size of 4096 bits, and protected by the passphrase 'betty'

# Define variables
KEY_NAME="school"
BITS=4096
PASSPHRASE="betty"

# Generate RSA key pair
ssh-keygen -t rsa -b $BITS -N "$PASSPHRASE" -f "$KEY_NAME"
